### PR TITLE
Fix cursor jumping to end of input

### LINKED ISSUE #217: Cursor jumps to end of input when inputValue is a controlled prop
- `downshift` version: 1.11.0
- `node` version: 6.9 (and codesadbox.io, could not find out, what they're using)
- `npm` (or `yarn`) version: yarn 1.1.0 (and whatever codesandbox.io uses)

Problem description:
- Visit this [codesandbox](https://codesandbox.io/s/3qnr4j4lnq)
- type text
- move cursor to the left
- type a letter
- the letter will be added at the correct position, but the cursor will move to the end of the input instead of staying where you have typed

Relevant code or config

```javascript
class Demo extends React.Component {
  state = {
    inputValue: ""
  };

  render() {
    return (
      <div>
        <Downshift
          onStateChange={data => {
            return (
              data.hasOwnProperty("inputValue") &&
              this.setState({ inputValue: data.inputValue })
            );
          }}
          inputValue={this.state.inputValue}
        >
          {({ getInputProps }) => (
            <div>
              <input {...getInputProps()} />
            </div>
          )}
        </Downshift>
      </div>
    );
  }
}
```

### PR DESCRIPTION
**Pull request by robin-drexler**
#217

Continuation of https://github.com/paypal/downshift/pull/229

**What**:
Provide an onInputValueChange callback to allow to update controlled prop before its old value is used to re-render the children, causing the cursor in the input to jump to the end in the next render.

**Why**:
fixes #217 

**Checklist**:

- [ ] Documentation
- [x] Tests
- [ ] Ready to be merged -> docs missing 
- [ ] Added myself to contributors table 

@kentcdodds I'd like to get your opinion on this change before adding documentation for it.
Do you think this is a direction worth pursuing?

### CODE REVIEW

**Comment by robin-drexler** [comment]
I've added a story (to be removed again) to showcase the issue and to tinker around with.
I tried to move the `onInputValueChange` callback into the setState function, but that caused the initial issue to show up again.

File: src/downshift.js [hunk 1]
```diff
@@ -287,6 +290,14 @@ class Downshift extends Component {
           onChangeArg = stateToSet.selectedItem
         }
         stateToSet.type = stateToSet.type || Downshift.stateChangeTypes.unknown
+
+        if (stateToSet.hasOwnProperty('inputValue')) {
```
Comment (kentcdodds) [inline src/downshift.js]: Unfortunately, this wont work with [when we call `reset`](https://github.com/paypal/downshift/blob/1385fc9dc5bc5e93ef68c863c971946a3e29db63/src/downshift.js#L621) which users can do themselves _or_ when the user clicks outside the menu... 🤔 This is because `stateToSet` in that case is a function, but it does set the `inputValue`. So I'm thinking that we can do this, but we _also_ have to handle the case where `stateToSet` is a function. I think the best thing to do would be to test this by calling `reset` and make sure that `onInputValueChange` is called in that case (in addition to the other tests you already have). Then we'll figure out the best way to implement that.

Comment (robin-drexler) [reply src/downshift.js]: Did you see my comment here? https://github.com/paypal/downshift/pull/229#discussion_r145216365
I'm not sure yet that invoking the `onInputValueChange` callback inside the `setState` function works at all to fix the issue at hand. I'd like to prove that first before addressing issues like the different incarnations of  `stateToSet`.

Sorry for the confusion with two opened PRs. :/

Comment (kentcdodds) [reply src/downshift.js]: I did see your comment. But as I said, the existing code will _never_ call `onInputValueChange` when `reset` is called. We definitely need to call `onInputValueChange` any time the `inputValue` is called.

I think that the solution is good as is, then we add _more_ code for the case when the `stateToSet` is a function (which only applies in the `reset` case). Luckily for us, when `reset` happens, the original issue won't be a problem.

Comment (robin-drexler) [reply src/downshift.js]: The issue I'm having is that calling `onInputValueChange` inside `setState` function does not appear to fix the issue with the cursor jumping to the end of the input. 

Or am I misunderstanding and with "the existing code" you were referring to my original version, where the `onInputValueChange` call was placed above the `setState`?

Sorry, I'm a bit confused right now.

Comment (kentcdodds) [reply src/downshift.js]: Ok, so the code you have already is great. We're not going to change it.

The problem is that the code you have doesn't cover the `reset` case because `stateToSet` is a function in that case (and it has to be that way). So if we merged this PR as is it would work great for everything except for when the user clicks outside the menu or tabs out of the menu (which is when `reset` is called).

To deal with this issue, we need more code. We need to handle the case where `stateToSet` is a function. If it is, then we need to do that inside of `setState`.

Luckily, when `stateToSet` is a function, then we wont have the problem of the cursor jumping to the end of the input because the focus will be elsewhere anyway.

Does that make sense?

Comment (robin-drexler) [reply src/downshift.js]: Yes, it does. Thanks for clearing things up! :)

**Comment by robin-drexler** [comment]
Implemented the function version of `stateToSet` as well and added a test for it.

**Comment by kentcdodds** [comment]
Would you like to [add yourself](../blob/master/CONTRIBUTING.md#add-yourself-as-a-contributor) to the [contributors table](../#contributors)?

**Comment by robin-drexler** [comment]
Thank you so much for your help. :)
I'll open a new PR for the contributions table.
