### PR TITLE
fix(getButtonProps): automatically focus on the button if necessary

### LINKED ISSUE #276: broken keyboard navigation in safari
* `downshift` version: 1.22.1
* `node` version: n/a
* `npm` (or `yarn`) version: n/a
* `chrome version:  62.0.3202.94`
* `safari version: 11.0.1 `

What you did:

In the dropdown example [here](http://downshift.netlify.com/?selectedKind=Examples&selectedStory=dropdown&full=0&down=1&left=1&panelRight=0), in safari when the dropdown is clicked the menu opens but trying to navigate the items with the keyboard fails to work, in the other examples it works fine. [Short video](https://streamable.com/rd3zb) of the issue.

I am also seeing this behaviour in a dropdown I built with `downshift`.

What happened:

Nothing happened. Should have update the highlighted index

### PR DESCRIPTION
**Pull request by kentcdodds**
**What**: auto-focus the target if the activeElement is the body

**Why**: Closes #276

**How**: Just change the logic a bit in the button click handler and improve the prop types.

**Checklist**:

* [ ] Documentation N/A
* [ ] Tests N/A
* [x] Ready to be merged
      
* [x] Added myself (or others) to contributors table
      

cc @httpete-ire and @philipyoungg :)

### CODE REVIEW

File: src/downshift.js [hunk 1]
```diff
@@ -561,6 +563,15 @@ class Downshift extends Component {
 
   button_handleClick = event => {
     event.preventDefault()
+    // handle odd case for Safari and Firefox which
+    // don't give the button the focus properly.
+    /* istanbul ignore if (can't reasonably test this) */
+    if (
+      this.props.environment.document.activeElement ===
+      this.props.environment.document.body
```
Comment (kentcdodds) [inline src/downshift.js]: I'm using this if statement because some folks may want to automatically focus the input or some other thing when the button is pressed. This gets around the bug 👌

Comment (philipyoungg) [reply src/downshift.js]: Oh 😍😍😍
